### ISSUE TITLE
!!!!!***** DEEPLINK NOT WORKING WHEN APP KILLED - WITH FRAGMENT ACTIVITY *******!!!!!!!!

### ISSUE THREAD

**Issue by madhu6264** [RodrigoSMarques/flutter_branch_sdk#111] opened 2021-06-26 10:35 UTC
Hi There,

Deeplinks listener not called when the app in the killed state, but we can't use Flutter activity some other plugins depends on flutter fragment activity.

Because of this issue, we have halted our release, please help me urgently.

**Comment by RodrigoSMarques** [comment] 2021-06-26 15:09
Hi @madhu6264 

There is an open issue #59  about this and it is described in the package about the lack of support for FlutterFragmentActivity. "[Note: This plugin not work with FlutterFragmentActivity in Android"](https://github.com/RodrigoSMarques/flutter_branch_sdk#flutter_branch_sdk).

But, I'm testing a new version where experimental support for FlutterFragmentActivity will be added.

Testing is ongoing, expected to be released next week. But changes will be released from the last version with null safety.

**Comment by RodrigoSMarques** [comment] 2021-06-26 15:09
Duplicate of #59

**Comment by RodrigoSMarques** [comment] 2021-06-28 03:45
Released version 3.3.0 with support for FlutterFragmentActivity

**Closed by RodrigoSMarques** 2021-06-28 03:45 UTC
