### ISSUE TITLE
clicked_branch_link  is to true when app is opened from deeplink and then putted in background and reopened

### ISSUE THREAD

**Issue by Not-Dhanraj** [RodrigoSMarques/flutter_branch_sdk#146] opened 2022-02-18 16:58 UTC
**Describe the bug**
When app is opened from a deeplink ,and deeplink page is popped. When app is putted in background by os. after these when app is reopened from recent apps then clicked_branch_link is true and same page is opened.

**To Reproduce**

https://user-images.githubusercontent.com/80586983/154726447-65e64f25-5ad9-4da5-a1dd-4265d23f7a08.mp4

**Expected behavior**
When app is reopened then clicked_branch_link should be false.

**Desktop (please complete the following information):**
 - Flutter: version: [e.g. 2.8.1]
 - Package version: [e.g. 5.0.0]

**Smartphone (please complete the following information):**

 - Device: [Samsung Tab S6 Lite]
 - OS: [Android 11]

**Additional context**

Here's my code to listen dynamic Links-

```  void listenDynamicLinks() async {
    streamSubscription = FlutterBranchSdk.initSession().listen((data) {
      controllerData.sink.add((data.toString()));
      if (data.containsKey('+clicked_branch_link') &&
          data['+clicked_branch_link'] == true) {
        appRouter.push(
          CustomWallDetailsPageRoute(
            name: '${data['name']}',
            author: '${data['author']}',
            description: '${data['description']}',
            url: '${data['url']}',
            category: '${data['category']}',
            id: '${data['id']}',
            thumb: '${data['thumb']}',
            resolution: '${data['custom_string']}',
            size: '${data['size']}',
            timeStamp: DateTime.parse('${data['timeStamp']}'.toString()),
          ),
        );
      }
      buo = BranchUniversalObject(
        canonicalIdentifier: 'walllcanic://',
        title: 'name - WallCanic Walls',
        imageUrl:
            'https://raw.githubusercontent.com/Not-Dhanraj/test-walls/main/icon.png',
        contentDescription: 'description',
        contentMetadata: BranchContentMetaData()
          ..addCustomMetadata('id', '${data['id']}')
          ..addCustomMetadata('name', '${data['name']}')
          ..addCustomMetadata('url', '${data['url']}')
          ..addCustomMetadata('author', '${data['author']}')
          ..addCustomMetadata('category', '${data['category']}')
          ..addCustomMetadata('description', '${data['description']}')
          ..addCustomMetadata('thumb', '${data['thumb']}')
          ..addCustomMetadata('resolution', '${data['resolution']}')
          ..addCustomMetadata('size', '${data['size']}')
          ..addCustomMetadata('timeStamp', '${data['timeStamp']}'),
        publiclyIndex: true,
      );
      eventStandart = BranchEvent.standardEvent(BranchStandardEvent.SHARE);
      FlutterBranchSdk.registerView(buo: buo!);
    }, onError: (error) {
      PlatformException platformException = error as PlatformException;
      Sentry.captureException(error);
      debugPrint(
          'InitSession error: ${platformException.code} - ${platformException.message}');
      controllerInitSession.add(
          'InitSession error: ${platformException.code} - ${platformException.message}');
    });
  }
```

my `streamSubscription`, `controllerInitSession` and `controllerData` are disposed correctly as shown in example

**Comment by RodrigoSMarques** [comment] 2022-02-24 05:08
I did tests with sample application and could not reproduce the error.

Can you test it out?

I merged #PR #147 , but in the example program, the behavior has not changed

**Comment by Not-Dhanraj** [comment] 2022-02-28 11:56
[branch_bug.zip](https://github.com/RodrigoSMarques/flutter_branch_sdk/files/8153084/branch_bug.zip)


Here's a demo app in which i was able to reproduce the bug. i basically copied and pasted example app code into this demo. also the provided keys are revoked.

**Comment by RodrigoSMarques** [comment] 2022-03-11 04:03
Test using this version.

Update your `pubspec.yaml` to

```dart
  flutter_branch_sdk:
    git:
      url: https://github.com/RodrigoSMarques/flutter_branch_sdk.git
      ref: dev
```

**Comment by Not-Dhanraj** [comment] 2022-03-20 06:32
Thanks for testing out. I couldn't test this, as i dont have access to my pc these days and i am using online ide in order to do my commits

**Comment by RodrigoSMarques** [comment] 2022-05-27 12:07
Version 5.1.0 with fix released

**Closed by RodrigoSMarques** 2022-05-27 12:07 UTC
Labels: bug
