### ISSUE TITLE
getShortUrl broken on web

### ISSUE THREAD

**Issue by stx** [RodrigoSMarques/flutter_branch_sdk#135] opened 2022-01-02 04:38 UTC
Flutter 2.8.1, Chrome. Same code works on iOS + Android.

getShortUrl() error: Expected a value of type 'String', but got one of type 'JavaScriptObject'
Error: success: false, errorCode: -1, errorMessage: getShortUrl() error}
    at Object.createErrorWithStack (http://localhost:1234/dart_sdk.js:5076:12)
    at Object._rethrow (http://localhost:1234/dart_sdk.js:40477:16)
    at async._AsyncCallbackEntry.new.callback (http://localhost:1234/dart_sdk.js:40473:13)
    at Object._microtaskLoop (http://localhost:1234/dart_sdk.js:40330:13)
    at _startMicrotaskLoop (http://localhost:1234/dart_sdk.js:40336:13)

```
    BranchUniversalObject buo = BranchUniversalObject(
      canonicalIdentifier: 'referral',
      canonicalUrl: 'https://mysite.com',
      publiclyIndex: false,
      locallyIndex: false,
    );

    BranchLinkProperties lp = BranchLinkProperties(
      feature: 'referral',
    )..addControlParam('referring_user_id', 'blah');

    BranchResponse<dynamic> response = await FlutterBranchSdk.getShortUrl(
      buo: buo,
      linkProperties: lp,
    );
```

**Comment by RodrigoSMarques** [comment] 2022-02-08 13:11
I tested it and couldn't reproduce the problem.

**Comment by RodrigoSMarques** [comment] 2022-02-17 13:24
@stx 
can i close this issue?

**Closed** 2022-02-17 17:24 UTC
Labels: bug
