### ISSUE TITLE
Unable to start the app due to unable to load Maven meta-data from jcenter/bintray

### ISSUE THREAD

**Issue by jseminck** [RodrigoSMarques/flutter_branch_sdk#186] opened 2022-10-31 07:39 UTC
**Describe the bug**
I am not able to start my app today, yesterday everything was fine. Not sure if this is a Branch SDK issue or the flutter library issue, but I plan to contact Branch support as well.

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve io.branch.sdk.android:library:5.2.+.
     Required by:
         project :app > project :flutter_branch_sdk
      > Failed to list versions for io.branch.sdk.android:library.
```

**To Reproduce**
1. Install the latest version of the dependency
2. Start the app

**Expected behavior**
3. App starts

**Comment by krishh-apnaklub** [comment] 2022-10-31 08:43
We are facing the same error in our Flutter project. But, since it is not so crucial for us to have the latest version, we have downgraded the `flutter_branch_sdk` to the `v5.1.1` and our app started to compile without any error.

Furthermore, I would like to mention [this Stackoverflow thread](https://stackoverflow.com/questions/74258160/is-jcenter-down) for your reference. It is about jCenter being down. I have not gone through it myself thoroughly, though.

**Comment by jseminck** [comment] 2022-10-31 09:15
Thank you, I will also try the downgrade.

I understood it's because jCenter is down. I also assume this is a branch SDK issue and I contacted Branch directly as well, with the assumption that they can publish a new version. Then the flutter dependency probably needs to update to the newer Android SDK version also, when/if it is released and available. 🙏

**Comment by followthemoney1** [comment] 2022-10-31 10:51
the temporary solution should works until will be fixed jCenter 
<img width="1254" alt="image" src="https://user-images.githubusercontent.com/8526612/198991516-4d6768e2-444b-4575-815f-5053fe86fda8.png">

can try this: 
```
allprojects {
    repositories {
        all { ArtifactRepository repo ->
            println repo.url.toString()
            if (repo.url.toString().startsWith("https://jcenter.bintray.com/")) {
                project.logger.warn "Repository ${repo.url} removed."
                remove repo
                maven { url "https://maven.aliyun.com/repository/jcenter" }
            }
        }
        google()
        mavenCentral()
    }
}
```

**Comment by michael-woolsey** [comment] 2022-10-31 13:44
Apparently `flutter_branch_sdk`  still thinks it requires something from `jcenter.bintray.com`:

> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve io.branch.sdk.android:library:5.2.+.
     Required by:
         project :app > project :flutter_branch_sdk
      > Failed to list versions for io.branch.sdk.android:library.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/io/branch/sdk/android/library/maven-metadata.xml.
            > Could not HEAD 'https://jcenter.bintray.com/io/branch/sdk/android/library/maven-metadata.xml'.
               > Read timed out

**Comment by ndahlquist** [comment] 2022-11-07 21:29
@michael-woolsey : for us, this was caused by a different package (`plaid_flutter`) invoking `jcenter()` on all projects... In case a different package is causing the issue for you, [this snippet](https://stackoverflow.com/a/57677542/1567183) was helpful for debugging. Best of luck- this is not a super fun thing to spend time on 😢

**Comment by michael-woolsey** [comment] 2022-11-07 23:31
Thanks @ndahlquist - I used the snippet from @followthemoney1 and that worked for me.

**Comment by RodrigoSMarques** [comment] 2022-11-12 03:01
Closing the issue

**Closed by RodrigoSMarques** 2022-11-12 03:01 UTC
Labels: bug
