### ISSUE TITLE
int android.content.Intent.getFlags()

### ISSUE THREAD

**Issue by HarshNT** [RodrigoSMarques/flutter_branch_sdk#255] opened 2023-11-06 13:41 UTC
**Error Logs**
E/MethodChannel#flutter_branch_sdk/message( 8335): Failed to handle method call
E/MethodChannel#flutter_branch_sdk/message( 8335): java.lang.NullPointerException: Attempt to invoke virtual method 'int android.content.Intent.getFlags()' on a null object reference
E/MethodChannel#flutter_branch_sdk/message( 8335): at android.app.ContextImpl.startActivity(ContextImpl.java:1122)
E/MethodChannel#flutter_branch_sdk/message( 8335): at android.app.ContextImpl.startActivity(ContextImpl.java:1103)
E/MethodChannel#flutter_branch_sdk/message( 8335): at android.content.ContextWrapper.startActivity(ContextWrapper.java:436)
E/MethodChannel#flutter_branch_sdk/message( 8335): at br.com.rsmarques.flutter_branch_sdk.FlutterBranchSdkPlugin.setupBranch(FlutterBranchSdkPlugin.java:447)
E/MethodChannel#flutter_branch_sdk/message( 8335): at br.com.rsmarques.flutter_branch_sdk.FlutterBranchSdkPlugin.onMethodCall(FlutterBranchSdkPlugin.java:252)
E/MethodChannel#flutter_branch_sdk/message( 8335): at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/MethodChannel#flutter_branch_sdk/message( 8335): at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#flutter_branch_sdk/message( 8335): at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/MethodChannel#flutter_branch_sdk/message( 8335): at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#flutter_branch_sdk/message( 8335): at android.os.Handler.handleCallback(Handler.java:958)
E/MethodChannel#flutter_branch_sdk/message( 8335): at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#flutter_branch_sdk/message( 8335): at android.os.Looper.loopOnce(Looper.java:205)
E/MethodChannel#flutter_branch_sdk/message( 8335): at android.os.Looper.loop(Looper.java:294)
E/MethodChannel#flutter_branch_sdk/message( 8335): at android.app.ActivityThread.main(ActivityThread.java:8177)
E/MethodChannel#flutter_branch_sdk/message( 8335): at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter_branch_sdk/message( 8335): at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
E/MethodChannel#flutter_branch_sdk/message( 8335): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)

flutter_branch_sdk: ^7.0.0

Android 13

Error occure when i use this await FlutterBranchSdk.init(
useTestKey: false, enableLogging: false, disableTracking: false); in main.dart.

**Comment by mueksh-b** [comment] 2023-11-06 20:04
@RodrigoSMarques 
The example code is working fine. But the issue is with the projects which use Kotlin instead of Java. after comparing the example code with my project, I found that if we use Kotlin and extend MainActivity with FlutterFragmentActivity then Branch SDK crashes and fails to initialize. Please take a look at the screenshot I've attached for more details. It may help you to figure it out.
![Screenshot 2023-11-07 at 1 26 28 AM](https://github.com/RodrigoSMarques/flutter_branch_sdk/assets/24774694/826719ca-b728-4c90-9d44-c4697c5e8517)

**Comment by RodrigoSMarques** [comment] 2023-11-06 20:09
The problem may be related to using FlutterFragmentActivity.

I'll investigate.

**Comment by HarshNT** [comment] 2023-11-07 05:05
@mueksh-b thank you for looking deep

**Comment by RodrigoSMarques** [comment] 2023-11-08 01:01
Hi @HarshNT  and @mueksh-b 

The cause of the problem is the use of FlutterFragmentActivity.

It has no relation to the language (Java or Kotlin).

I found the solution and I'm doing final tests. The plugin will work with FlutterActivity or FlutterFragmentActivity.

I will release a new version in the next few days.

**Comment by ahkela21** [comment] 2023-11-08 14:09
facing the same issue, waiting for fix thanks

**Comment by RodrigoSMarques** [comment] 2023-11-11 02:45
Resolved in version 7.0.1

**Closed by RodrigoSMarques** 2023-11-11 02:45 UTC
Labels: bug

**Comment by HarshNT** [comment] 2023-11-16 06:47
@RodrigoSMarques Thanks
