### ISSUE TITLE
trackContent hangs UI thread in Android in Flutter 2

### ISSUE THREAD

**Issue by omarhurani** [RodrigoSMarques/flutter_branch_sdk#91] opened 2021-03-19 02:15 UTC
We used custom tracking events which were triggered when users visit pages in the application.

After we upgraded to Flutter 2, we noticed that the transition animation between pages hangs for a second or so. After tracking down the issue in Flutter's Profile mode, turns out that calling the `FlutterBranchSdk.trackContent` method on Android was the cause (on Flutter's UI thread). We tried using another branch package (which is very old and un-updated) to no imporvements. We also tried using non-custom events and `FlutterBranchSdk.trackContentWithoutBuo`, but both resulted in the same performace issue.

The problem does not occur on iOS devices so my thought was with the Java Branch SDK or the method channels code involving it, but I haven't worked with Branch on native development platforms so I'm not familiar with such issues. 

I am not sure if the upgrade to Flutter 2 has anything to do with this, but we didn't notice the issue until then.

**Comment by RodrigoSMarques** [comment] 2021-03-20 02:24
Hi @omarhurani 

There was an issue related to Maintread, but this was fixed in version 1.3.2: #69 

Version 2.0.0 of the package uses a version of the latest Branch SDK that is 5.0.7.

The other versions use 5.0.5.

There may be a problem with the SDK.

I need to do some tests to evaluate.

**Comment by jk-akshay-arora** [comment] 2021-03-24 11:00
Any updates on this?

**Comment by RodrigoSMarques** [comment] 2021-03-24 11:45
I was unable to reproduce the problem. My app that has the same process of calling the method FlutterBranchSdk.trackContent has not yet been migrated to null safety, because of the dependencies.

Was the app normal in version 1.3.2?

Version 2.0 was created from it.

The difference is that version 1.3.2 uses version 5.0.5 of the Branch SDK and version 2.0 uses version 5.0.7

**Comment by omarhurani** [comment] 2021-04-01 11:42
As I mentioned, the same issue occurs with another package, [Flutter Branch IO Plugin](https://pub.dev/packages/flutter_branch_io_plugin), which seems to be discontinued. This is why I'm thinking that the problem is from the Branch SDK for Android, but I'm not sure.

**Comment by RodrigoSMarques** [comment] 2021-04-01 12:08
> As I mentioned, the same issue occurs with another package, [Flutter Branch IO Plugin](https://pub.dev/packages/flutter_branch_io_plugin), which seems to be discontinued. This is why I'm thinking that the problem is from the Branch SDK for Android, but I'm not sure.

You said that before version 2.0 of Flutter it was normal. After I upgraded to Flutter 2.0 the problem appeared.
I got it right?
I have some issues to check in the package this weekend. I'll check if I find anything.

**Comment by RodrigoSMarques** [comment] 2021-04-04 15:27
@omarhurani 

Can you do a test with this version?
```dart
  flutter_branch_sdk:
    git:
      url: https://github.com/RodrigoSMarques/flutter_branch_sdk.git
      ref: dev
```

**Comment by omarhurani** [comment] 2021-04-06 13:16
I have tried to mess with the MethodChannel handler for `trackContent` and it seems that the call from `event.addContentItems(buo).logEvent(context);` is the one causing the issue for me. I tried running in a separate Java Thread and the issue went away (I don't know if this is something that should be done or not).

```java
@UiThread
private void trackContent(MethodCall call) {
    LogUtils.debug(DEBUG_NAME, "trackContent call");
    if (!(call.arguments instanceof Map)) {
        throw new IllegalArgumentException("Map argument expected");
    }
    HashMap<String, Object> argsMap = (HashMap<String, Object>) call.arguments;
    final BranchUniversalObject buo = branchSdkHelper.convertToBUO((HashMap<String, Object>) argsMap.get("buo"));
    final BranchEvent event = branchSdkHelper.convertToEvent((HashMap<String, Object>) argsMap.get("event"));

    Runnable logEventRunnable = new Runnable() {
        @Override
        public void run() {
            event.addContentItems(buo).logEvent(context);
        }
    };

    Thread logEventThread = new Thread(logEventRunnable);
    logEventThread.start();

}
``` 

I also tried to remove `@UiThread` (not quite sure what it does but gave it a try anyway), but the issue was unaffected.

I haven't worked with MethodChannels myself so I'm not sure about what I'm looking for/testing.

**Comment by RodrigoSMarques** [comment] 2021-04-06 14:43
The methods that do not return information to the Flutter, were not marked for UiThread and this could cause the problem.

The @UiThread annotation should have an effect.

[https://flutter.dev/docs/development/platform-integration/platform-channels#channels-and-platform-threading](https://flutter.dev/docs/development/platform-integration/platform-channels#channels-and-platform-threading)

I will evaluate this change that you made. It is also suggested in the documentation

**Comment by RodrigoSMarques** [comment] 2021-04-12 12:40
@omarhurani 

Can you send me a video demonstrating the problem?
Is the animation between pages simple or complex?
I need information to reproduce the problem.

**Comment by omarhurani** [comment] 2021-04-16 14:30
The animation is a basic MaterialRoutePage animation, nothing fancy. The project is large so it isn't easy to see if the problem is caused by incompatability with other things, but I'll try and see

**Comment by RodrigoSMarques** [comment] 2021-04-30 04:25
@omarhurani 
See this. I will generate a new release to use that version

https://github.com/BranchMetrics/android-branch-deep-linking-attribution/releases/tag/5.0.8

**Comment by RodrigoSMarques** [comment] 2021-06-08 00:35
New version 3.2 uses new version of Branch SDK which fixes this problem.

**Closed by RodrigoSMarques** 2021-06-08 00:35 UTC
