### ISSUE TITLE
Deep linking not working for Skype.

### ISSUE THREAD

**Issue by Shahkhalid2710** [RodrigoSMarques/flutter_branch_sdk#352] opened 2024-07-23 10:04 UTC
It is working fine in others apps but not in Skype.
In Skype, og:title, og:descrition and og: image not showing.

Example Code:

`class HomeNewScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Branch.io Demo'),
      ),
      body: Center(
        child: ElevatedButton(
          onPressed: () async {
            String propertyId = '123';
            String propertyName = 'Beautiful Beach House';
            String propertyDescription =
                'A beautiful beach house with stunning ocean views.';
            String propertyImageUrl =
                'https://fastly.picsum.photos/id/1/5000/3333.jpg?hmac=Asv2DU3rA_5D1xSe22xZK47WEAN0wjWeFOhzd13ujW4';

            BranchUniversalObject buo = BranchUniversalObject(
              canonicalIdentifier: 'property/$propertyId',
              title: propertyName,
              contentDescription: propertyDescription,
              imageUrl: propertyImageUrl,
              contentMetadata: BranchContentMetaData()
                ..addCustomMetadata('property_id', propertyId)
                ..addCustomMetadata('property_name', propertyName)
                ..addCustomMetadata('og:title', propertyName)
                ..addCustomMetadata('og:description', propertyDescription)
                ..addCustomMetadata('og:image', propertyImageUrl)
                ..addCustomMetadata('og:url', propertyImageUrl)
                ..addCustomMetadata('og:type', "website"),
              publiclyIndex: true,
              locallyIndex: true,
            );

            BranchLinkProperties lp = BranchLinkProperties(
              channel: 'facebook',
              feature: 'sharing',
              stage: 'new share',
              campaign: 'property campaign',
            );

            BranchResponse<dynamic> response =
                await FlutterBranchSdk.getShortUrl(
              buo: buo,
              linkProperties: lp,
            );

            debugPrint("Api response is ${response}");

            if (response.success) {
              String url = response.result;
              Share.share('$url', subject: "Social");

              // Share the URL or use it as needed
            } else {
              debugPrint(
                  'Error creating Branch link: ${response.errorMessage}');
            }
          },
          child: Text('Create Branch Link'),
        ),
      ),
    );
  }
}
`

**Comment by RodrigoSMarques** [comment] 2024-07-23 17:04
Hi @Shahkhalid2710 

This package calls Branch Native SDK functions on each platform.

The problem reported is not in the Flutter plugin, but in the Native SDK.

Please open an issue in the platform repository:

- iOS: [https://github.com/BranchMetrics/ios-branch-deep-linking-attribution](https://github.com/BranchMetrics/ios-branch-deep-linking-attribution)
- Android: [https://github.com/BranchMetrics/android-branch-deep-linking-attribution](https://github.com/BranchMetrics/android-branch-deep-linking-attribution)

Or open a support ticket for Branch at the [link](https://help.branch.io/using-branch/page/submit-a-ticket)

**Comment by RodrigoSMarques** [comment] 2024-07-23 17:13
Have you checked the documentation?

Are there values ​​to be used through the SDK. Check Branch parameters for [Open Graph](https://help.branch.io/using-branch/docs/creating-a-deep-link#open-graph)

**Comment by RodrigoSMarques** [comment] 2024-07-24 12:13
it's a problem in Skype and not in the SDK. 

can we close the issue?

**Comment by RodrigoSMarques** [comment] 2024-07-24 13:41
> When I share link from others apps like Airbnb, Youtube, Image are display in Skype.
> 
> Is there any way available, we can display card same as youtube in Skype ?

I did a Google search (Skype Weblink Previews don't work) and found several reports on Google of people complaining that the image doesn't load when sharing a link.

If it works on other platforms, I believe the problem is not with the plugin or the Branch SDK, but is a problem with Skype.

Therefore, I see that nothing can be done here.

**Comment by RodrigoSMarques** [comment] 2024-08-14 00:47
Closed. No activity in the last 14 days.
If necessary open again.

**Closed by RodrigoSMarques** 2024-08-14 00:47 UTC
Labels: bug

**Comment by preetpatel21** [comment] 2024-11-15 09:37
I am getting same issue. Not able to preview the image.

Future<String> generateDeepLink(String moduleName, String postId) async {
    BranchUniversalObject buo = BranchUniversalObject(
      canonicalIdentifier: 'flutter/branch',
      title: "Let's Test Image title", 
      contentDescription: "Let's Test Image Description",
      imageUrl:
          'https://icons.veryicon.com/png/128/miscellaneous/tmc-1/confirm-26.png',
      keywords: [moduleName, 'DTS'],
      contentMetadata: BranchContentMetaData()
        ..addCustomMetadata('post_id', postId)
        ..addCustomMetadata('key', moduleName)
        ..addCustomMetadata('og:title', "Let's Test Image title")
        ..addCustomMetadata('og:description', "Let's Test Image Description")
        ..addCustomMetadata('og:image',
            'https://icons.veryicon.com/png/128/miscellaneous/tmc-1/confirm-26.png')
        ..addCustomMetadata('og_type', 'website')
        ..addCustomMetadata('og:url',
            'https://icons.veryicon.com/png/128/miscellaneous/tmc-1/confirm-26.png'),
      publiclyIndex: true,
      locallyIndex: true,
    );
    BranchLinkProperties lp = BranchLinkProperties(
        //alias: 'flutterplugin', //define link url,
        channel: 'facebook',
        feature: 'sharing',
        stage: 'new share',
        tags: ['one', 'two', 'three']);
    BranchResponse response =
        await FlutterBranchSdk.getShortUrl(buo: buo, linkProperties: lp);
    String deeplinkURL = '';
    if (response.success) {
      print('Link generated: ${response.result}');
      deeplinkURL = response.result;
    } else {
      print('Error : ${response.errorCode} - ${response.errorMessage}');
      deeplinkURL = '';
    }
    return deeplinkURL;
  }
