### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by guilhermeagostinelli** [RodrigoSMarques/flutter_branch_sdk#84] opened 2021-02-23 16:58 UTC
Hello,

All of a sudden I'm unable to execute the app in release mode. Guess it must be something related to the JCenter unavailability.

<details>
<summary>flutter run --release</summary>
<p>
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Execution failed for task ':app:lintVitalRelease'.                      
> Could not resolve all artifacts for configuration ':app:debugAndroidTestRuntimeClasspath'.
   > Could not resolve com.google.android.gms:play-services-ads-identifier:16+.
     Required by:                                                       
         project :app > project :flutter_branch_sdk                     
      > Failed to list versions for com.google.android.gms:play-services-ads-identifier.
         > Could not list versions using M2 pattern 'https://jcenter.bintray.com/[organisation]/[module]/[revision]/[artifact]-[revision](-[classifier])(.[ext])'.
            > Could not get resource 'https://jcenter.bintray.com/com/google/android/gms/play-services-ads-identifier/'.
               > Could not GET 'https://jcenter.bintray.com/com/google/android/gms/play-services-ads-identifier/'.
                  > Read timed out                                      
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 1m 50s                                                  
Running Gradle task 'assembleRelease'...                                
Running Gradle task 'assembleRelease'... Done                     110.6s
Exception: Gradle task assembleRelease failed with exit code 1
</p>
</details>

<details>
<summary>flutter doctor -v</summary>
<p>
[✓] Flutter (Channel stable, 1.22.6, on Linux, locale en_US.UTF-8)
    • Flutter version 1.22.6 at /home/guilherme/Downloads/flutter
    • Framework revision 9b2d32b605 (5 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/guilherme/Android/Sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_SDK_ROOT = /home/guilherme/Android/Sdk
    • Java binary at: /home/guilherme/Downloads/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at /home/guilherme/Downloads/android-studio
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.53.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.19.0

[✓] Connected device (2 available)
    • motorola one hyper (mobile)        • 0066348421    • android-arm64 • Android 10 (API 29)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86   • Android 10 (API 29) (emulator)

• No issues found!
</p>
</details>

**Comment by guilhermeagostinelli** [comment] 2021-02-23 17:26
Maybe upgrading the `play-services-ads-identifier` in the `build.gradle` file from

`implementation 'com.google.android.gms:play-services-ads-identifier:16+'`

to 

`implementation 'com.google.android.gms:play-services-ads-identifier:17.0.0'`

can work, I'm just unsure whether that would cause any impact on the Branch SDK functionalities.

**Comment by RodrigoSMarques** [comment] 2021-02-23 17:41
Branch documentation instructs you to use [version 16] (https://help.branch.io/developers-hub/docs/android-basic-integration#install-branch)
This morning, I was handling an error and I tested and compiled the sample application for Android (and also iOS) without any errors.

**Comment by guilhermeagostinelli** [comment] 2021-02-23 17:47
Hi @RodrigoSMarques thanks for the reply.

This morning I was also able to properly execute the app. The problem seemed to start this afternoon all of a sudden.

Could you please give it a double check now?

**Comment by guilhermeagostinelli** [comment] 2021-02-24 20:53
The problem is not present anymore. jcenter.bintray.com is back online.

**Comment by guilhermeagostinelli** [comment] 2021-05-12 20:42
Hello @RodrigoSMarques ,

I'm having the problem again which makes it impossible to run the app in release mode.

Now with a different error message:

```
* What went wrong:                                                      
Execution failed for task ':app:lintVitalRelease'.                      
> Could not resolve all artifacts for configuration ':app:debugAndroidTestRuntimeClasspath'.
   > Could not resolve com.google.android.gms:play-services-ads-identifier:16+.
     Required by:                                                       
         project :app > project :flutter_branch_sdk                     
      > Failed to list versions for com.google.android.gms:play-services-ads-identifier.
         > Unable to load Maven meta-data from https://google.bintray.com/exoplayer/com/google/android/gms/play-services-ads-identifier/maven-metadata.xml.
            > Could not get resource 'https://google.bintray.com/exoplayer/com/google/android/gms/play-services-ads-identifier/maven-metadata.xml'.
               > Could not GET 'https://google.bintray.com/exoplayer/com/google/android/gms/play-services-ads-identifier/maven-metadata.xml'. Received status code 403 from server: Forbidden
```

I'm running on Flutter v2.0.6 (currently the latest stable version).

**Comment by RodrigoSMarques** [comment] 2021-05-12 21:24
You have probably updated your project's Gradle version and this may be causing the problem.

https://stackoverflow.com/questions/59482329/flutter-problems-could-not-resolve-all-artifacts-for-configuration-classpath

**Comment by guilhermeagostinelli** [comment] 2021-05-13 14:43
Hi @RodrigoSMarques , thanks for the reply. The problem is gone for me too. It seems that there's some instability with the servers that serve the play-services-ads-identifier:16+ lib

Yesterday during almost the whole day I had to change `implementation 'com.google.android.gms:play-services-ads-identifier:16+'` to `implementation 'com.google.android.gms:play-services-ads-identifier:17.0.0'` in my app/build.gradle file otherwise I couldn't even execute the project in debug mode.

Then, when trying to run `flutter run --release`, I got the aforementioned error message.

Today the server that serves the play-services-ads-identifier:16+ lib seems to be back online and I'm able to debug and build the app again independently of using 16+ or 17.0.0 in my app/build.gradle file.

**Comment by guilhermeagostinelli** [comment] 2021-05-13 14:49
I'll close this issue then, but it seems just a matter of time until play-services-ads-identifier:16+ is unavailable again.

**Comment by guilhermeagostinelli** [comment] 2021-07-23 14:05
Hello,

`flutter build appbundle` is fine but I'm unable to run `flutter run --release`

It gives me the following error:

```
* What went wrong:                                                      
Execution failed for task ':app:lintVitalRelease'.                      
> Could not resolve all artifacts for configuration ':app:debugAndroidTestRuntimeClasspath'.
   > Could not resolve com.google.android.gms:play-services-ads-identifier:16+.
     Required by:                                                       
         project :app > project :flutter_branch_sdk                     
      > Failed to list versions for com.google.android.gms:play-services-ads-identifier.
         > Unable to load Maven meta-data from https://google.bintray.com/exoplayer/com/google/android/gms/play-services-ads-identifier/maven-metadata.xml.
            > Could not get resource 'https://google.bintray.com/exoplayer/com/google/android/gms/play-services-ads-identifier/maven-metadata.xml'.
               > Could not GET 'https://google.bintray.com/exoplayer/com/google/android/gms/play-services-ads-identifier/maven-metadata.xml'. Received status code 403 from server: Forbidden
```

**Comment by RodrigoSMarques** [comment] 2021-07-24 01:31
Solution [here](https://github.com/RodrigoSMarques/flutter_branch_sdk/issues/97#issuecomment-877698669)

**Comment by RodrigoSMarques** [comment] 2021-07-24 01:32
Duplicate of #97

**Comment by RodrigoSMarques** [comment] 2021-08-14 02:21
Closed. No activity in the last 14 days.
If necessary open again.

**Closed by RodrigoSMarques** 2021-08-14 02:21 UTC
